
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_TYPE = 'SET_TYPE';
export const SET_USER = 'SET_USER'
export const SET_USER_ID = 'SET_USER_ID';
export const SET_IMAGE = "SET_IMAGE"
export const UPDATE_USER = "UPDATE_USER"
export const APPEND_BUSINESS = "APPEND_BUSINESS"
export const REPLACE_BUSINESSES = "REPLACE_BUSINESSES"
export const DELETE_BUSINESS_ID = 'DELETE_BUSINESS_ID'
export const DELETE_B = "DELETE_B"

// UI
export const SET_EDIT_PROFILE = "SET_EDIT_PROFILE"
export const SET_ADD_BUSINESS = 'SET_ADD_BUSINESS'
export const DELETE_BUSINESS_DIALOG = 'DELETE_BUSINESS_DIALOG'